version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: docker/web.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: docker/app.docker
    volumes:
      - ./:/var/www
    links:
      - database
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=database"
      - "APP_DEBUG=true"
  database:
    image: postgres:14.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=diplom    